[profile.default]
src     = "src"
out     = "out"
libs    = ["lib"]
solc    = "0.8.25"
optimizer = true
optimizer_runs = 200

[profile.default.rpc_endpoints]
base          = "${BASE_RPC_URL}"
base_sepolia  = "${BASE_SEPOLIA_RPC_URL}"

[profile.default.etherscan]
base         = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }

[fmt]
line_length = 100
tab_width   = 4
